spring:
  # dataSource settings
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Taipei
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
     
  # sessionFactory settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  # Redis
  redis:
    host: localhost
    port: 6379
    
  # ViewResolver Settings
  mvc:
    view:
      prefix: /WEB-INF/views

server:
  port: 8082
